# Generated by Django 4.2.4 on 2023-08-31 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='stand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.stand'),
        ),
    ]
